### ISSUE TITLE
out-of-order WEC RPC server must be running to configure channels

### ISSUE THREAD

**Issue by olamotte** [ElasticSA/wec_pepped#1]
Hello,

Thanks for the great cookbook - there's a minor issue I've spotted, maybe you'll be able to reproduce it.
I'm setting this on a greenfield Windows server 2019.

Under: Set up the WEC subscriptions
I'm installing the channels (Step 1), but configuring custom channels (Step 2) fails silently, and then Step 3 is a hard fail. 
My understanding is that Step 2 fails, as the Subscription service is not yet running. 

Jumping to Step 4 and back to Step 2 solved the issue and the subscriptions were created after that. 

Cheers

**Comment by ThorbenJ** [comment]
Hi.

Nice catch, an artefact of documenting after testing. Although configure channels should always have worked as channels are not just for WEC, they can be used locally. You are right however, wecutil create/update subscription will fail if the WEC service is not running.

I have updated the WEC Cookbook swapping steps 3 and 4. With the WEC Service running (the new) step 4 script runs correctly.

BR
Thorben
